config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  resources :days, only: :show
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/day.rb
class Day 
  attr_reader :day
  def initialize(day=Date.today)
    @day = day 

  end 

  def tasks
     Task.where date: @day 
  end 
end 

app/models/task.rb
class Task < ApplicationRecord
  
  validates :name, presence: true
  validates :date, presence: true
  before_validation :set_enddate
  validate :timegood, :timedaygood

private
  def set_enddate
    if enddate.blank?
      self.enddate = date
    end 
  end  

  def timegood
    if enddate < date
      errors.add(:enddate, "End date must be after start date!")
    end
  end 

  def timedaygood
    if time < starttime
      errors.add(:time, "End time must be after start time!")
    end
  end 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true
end

app/controllers/days_controller.rb
class DaysController < ApplicationController

  def show
    @day = Day.new day  
  end
  
private 
 def day 
  Date.parse(params[:id].to_s)
 end 


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
 
 

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
skip_before_filter :verify_authenticity_token


def index
  @tasks = Task.all 
   @some_instance_vairable = Task.new
end 

def new
  @task = Task.new
end 

def show
  @task =Task.find(params[:id])
end 


def edit 
  @task =Task.find(params[:id])
   respond_to do |format|
    format.html
    format.js
  end
end

def create
  @task = Task.create(task_params) 
    if @task.errors.present?
      render :new, status: :unprocessable_entity 
    else
      redirect_to request.referrer
   end
end 

def update
  @task = Task.find(params[:id])
  @task.update_attributes(task_params)
end 

def destroy
  @task = Task.find(params[:id])
  @task.destroy
  redirect_to root_path
  flash[:alert] = "Task deleted"
end

private

  def set_up_instance_variable
     @some_instance_vairable = Task.new
  end

  def task_params
    params.require(:task).permit(:name, :datetime, :date, :notes, :enddate, :time, :starttime)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/days_helper.rb
module DaysHelper



def datedisplay(num)
 
  def  get_month_name(month)
 case month
    when 1 then name = "January"
    when 2 then name = "February"
    when 3 then name = "March"
    when 4 then name = "April"
    when 5 then name = "May"
    when 6 then name = "June"
    when 7 then name = "July"  
    when 8 then name = "August"
    when 9 then name = "September"
    when 10 then name = "October"
    when 11 then name = "November"
    when 12 then name = "December"
   end
    return name   
  end 
  
   def ordinalnum(num)
  numtotens = num.to_i % 10
  numtohundreds = num.to_i % 100
  if numtohundreds ==11 
    return "#{num}th" 
  elsif numtohundreds == 12
    return  "#{num}th" 
  elsif numtohundreds ==13 
    return  "#{num}th" 
  elsif numtotens == 1
    return  "#{num}st"
  elsif numtotens == 2
    return "#(num)nd"
  elsif numtotens == 3
    return "#{num}rd"
  elsif numtotens >= 4
    return "#{num}th"
  else numtotens == 0
     return "#{num}th"
  end 
end
 
      
  datearray = []
  datearray = num.to_s.split('-')
  year = datearray[0]
  month = datearray[1].tr('0','').to_i
  day = datearray[2]
 
  monthword = get_month_name(month)
  dayword = ordinalnum(day)    
 return "Tasks for #{monthword} #{dayword}, #{year}"
end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper

def shortday(date)
  day = date.to_s[-2,2]
  return day
end 


def timechop(time)
 timeshow = time.to_s[11,5]
 return timeshow
end

def idcreate(date)
  id = date.to_s.tr('-','')
  return id
 end 


def get_month_name(id)
 case id
    when 1 then name = "January"
    when 2 then name = "February"
    when 3 then name = "March"
    when 4 then name = "April"
    when 5 then name = "May"
    when 6 then name = "June"
    when 7 then name = "July"  
    when 8 then name = "August"
    when 9 then name = "September"
    when 10 then name = "October"
    when 11 then name = "November"
    when 12 then name = "December"
  end
  return name
end

def datedisplay(num)
 
  def  get_month_name(month)
 case month
    when 1 then name = "January"
    when 2 then name = "February"
    when 3 then name = "March"
    when 4 then name = "April"
    when 5 then name = "May"
    when 6 then name = "June"
    when 7 then name = "July"  
    when 8 then name = "August"
    when 9 then name = "September"
    when 10 then name = "October"
    when 11 then name = "November"
    when 12 then name = "December"
   end
    return name   
  end 
  
   def ordinalnum(num)
  numtotens = num.to_i % 10
  numtohundreds = num.to_i % 100
  if numtohundreds ==11 
    return "#{num}th" 
  elsif numtohundreds == 12
    return  "#{num}th" 
  elsif numtohundreds ==13 
    return  "#{num}th" 
  elsif numtotens == 1
    return  "#{num}st"
  elsif numtotens == 2
    return "#(num)nd"
  elsif numtotens == 3
    return "#{num}rd"
  elsif numtotens >= 4
    return "#{num}th"
  else numtotens == 0
     return "#{num}th"
  end 
end
 
      
  datearray = []
  datearray = num.to_s.split('-')
  year = datearray[0]
  month = datearray[1].tr('0','').to_i
  day = datearray[2]
 
  monthword = get_month_name(month)
  dayword = ordinalnum(day)    
 return "Tasks for #{monthword} #{dayword}, #{year}"
end

end

app/views/days/show.html.erb
<script>
  $(document).ready(function() {   
    $(".btn-info").click(function() {
      console.log($(this).data("edit-url"));
      var url = $(this).data("edit-url") + ".js"; 
        $.getScript(url, function(result){
          console.log(result);
        });
       });
      });

   //get date set as default for input field
    $(document).ready(function() {   
    $(".newdaytask").click(function() {
      var date = $(this).data("date"); 
      console.log(date);
        $('.datestart').val(date);
        });
    });

//datepicker for new task date
$(document).ready(function(){
  $(".datepicker").datepicker({ 
      dateFormat: 'yy-mm-dd',
      showOtherMonths: true,
      selectOtherMonths: true
    });
});

//timepicker 
$(document).ready(function(){
  $(".timeend, .timestart").timepicker({'step': 15});
});


</script>



<%ordereddays = @day.tasks.sort_by &:starttime%>
<div class = "col-6 offset-3 booyah-box">
<h1 class = "text-center"/> <%=datedisplay(ordereddays.first.date)%> </h1>
<hr/>
<% ordereddays.each do |show| %>
 
<div class="card">
<p><b><%= show.name %></b></p>

<hr class = "boxline"/>
<p> <b>Time:</b> <%= show.starttime.strftime('%l:%M %p')%> to  <%= show.time.strftime('%l:%M %p')%></p>
<hr class = "boxline"/>
<p><b> Notes:</b>
<%= show.notes %></p>
<div class ="text-right">
<div class="buttonfix">
<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal" data-edit-url="<%=edit_task_path(show) %>">Update</button>
</div>
<div class="buttonfix">
<%= button_to "Delete",task_path(show), method: :delete, class: "btn btn-danger",  data:{confirm: "Are you sure you want to delete this task?"} %>
</div>
</div>
</div>
<% end %>


<div class = "text-right">
<button type="button" class="btn btn-success newdaytask" data-toggle="modal"  data-target ='#newModal' data-date=<%=ordereddays.first.date%>> Add New Event</button>
</div>


<!-- Modal update -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Update Task</h4>
      </div>
      <div class="modal-body" id="form-placeholder">
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

<!--Modal new -->
<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">New Tasks</h4>
      </div>
      <div class="modal-body">
      <%= simple_form_for Task.new,  :html =>{ class: 'booyah-box col-12'} do |f| %>
    <%= f.input :name %>
    <%= f.input :date, :as => :string,  input_html: {class: 'datepicker datestart', value: ''} %>
    <!--<%= f.input :enddate, :as => :string, :label => 'End Date', input_html: {class: 'datepicker'} %> -->
    <%= f.input :starttime, :as => :string, :label => 'Start Time', input_html: {class: 'timestart'}%>
    <%= f.input :time, :as=> :string, :label => 'End Time', input_html: {class: 'timeend'}%>
    <%= f.input :notes %>
    <%= f.submit class: 'btn btn-warning' %>
  <% end %>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Calendar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all'  %>
    <%= javascript_include_tag 'application' %>


  </head>

  <body>
  <!---Navbar-->
<nav class="navbar navbar-toggleable-sm navbar-inverse bg-primary">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#collapsingNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand abs" href="#">Calendar Project</a>
    <div class="navbar-collapse collapse" id="collapsingNavbar">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#features">Link</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#myAlert" data-toggle="collapse">Link</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="" data-target="#myModal" data-toggle="modal">About</a>
            </li>
        </ul>
    </div>
</nav>
  <br class= "clr"/>

    <%= yield %>
  </body>
</html>


<!-- , 'data-turbolinks-track': 'reload'
, 'data-turbolinks-track': 'reload' -->

app/views/static_pages/index.html.erb
<header>
  
  <h1>Calendar of Fun</h1>
  
</header>

app/views/tasks/_form.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href= http://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.0/themes/smoothness/jquery-ui.css /> 

  <!-- Time picker link -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.8.1/jquery.timepicker.min.css"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.8.1/jquery.timepicker.min.js"></script>

<script>
//datepicker for new task date
$(document).ready(function(){
  $(".datepicker").datepicker({ 
      dateFormat: 'yy-mm-dd',
      showOtherMonths: true,
      selectOtherMonths: true
    });
});

//timepicker 
$(document).ready(function(){
  $(".timeend, .timestart").timepicker({'step': 15});
});


</script>



<%= simple_form_for @task, :html =>{ class: 'booyah-box col-12'} do |f| %>

    <%= f.input :name %>
     <%= f.input :date, :as => :string,  input_html: {class: 'datepicker'} %>
     <!--<%= f.input :enddate, :as => :string, :label => 'End Date', input_html: {class: 'datepicker'} %> -->
    <%= f.input :starttime, :as => :string, :label => 'Start Time', input_html: {class: 'timestart', value: timechop(@task.starttime)} %>
    <%= f.input :time, :as=> :string, :label => 'End Time', input_html: {class: 'timeend', value: timechop(@task.time)}%>
    <%= f.input :notes %>
    <%= f.submit class: 'btn btn-warning' %>
  <% end %>

app/views/tasks/edit.html.erb
<%= render partial: "form" %>

app/views/tasks/edit.js.erb
$("#form-placeholder").html('<%= j(render partial: "form", layout: false)  %>');

app/views/tasks/index.html.erb
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <link rel="stylesheet" href= https://ajax.aspnetcdn.com/ajax/jquery.ui/1.10.0/themes/smoothness/jquery-ui.css /> 

  <!-- Time picker link -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.8.1/jquery.timepicker.min.css"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-timepicker/1.8.1/jquery.timepicker.min.js"></script>

<!-- datepair.js -->

<!--   Makes the dialog css show up correctly -->

<script >
$(document).ready(function() {
         
 // draggable and dropable events with ajax update
    $('.tasks').draggable({
        helper: 'clone'
    });

    $('.cells').droppable({ 
      tolerance: 'pointer', 
      accept: '.tasks',
      drop: function(event, ui){
       
         var id = $(ui.draggable).attr('id');
         var taskinfo = $(ui.draggable).html();
         var day = $(this).attr('id');
         

         $.ajax({type: 'PUT', url: "http://localhost:3030/tasks/" + id, data: { task: {"date": day }}});
            
            var droppedItem = $(ui.draggable).clone();
            $(".linkdiv", this).prepend(droppedItem);
            $(droppedItem).draggable({
                      helper: 'clone'
                  });
            $(ui.draggable).remove();

              $('.icon, .iconpencil .iconcopy').hide();  
              $('.tasks').hover(function(){  
              $('.icon, .iconpencil .iconcopy', this).show(0);  
                }, function(){
                 $('.icon, .iconpencil .iconcopy', this).hide(0); 
                });
            

          }
        });
       });

//copy 
$(document).ready(function() {
$('.iconcopy').draggable({
        helper: 'clone'
    });
  });

//ajax delete function 
$(document).ready(function() {
  $('.icon').click(function(){
    var iddelete = $(this).attr('data-id');
    if (confirm("Are you sure you want to delete this task?")){
    // alert(iddelete);

    $.ajax({ type: 'DELETE', url: "http://localhost:3030/tasks/" + iddelete, data:{} });
      $(this).parent().remove();


        }
      });
     });

//icon hover hide    
$(document).ready(function() {
  $('.icon, .iconpencil, .iconcopy').hide();  
  $('.tasks').hover(function(){  
  $('.icon, .iconpencil, .iconcopy', this).show(0); 
    }, function(){
     $('.icon, .iconpencil, .iconcopy', this).hide(0); 
    });
   });

//datepicker for new task date
$(document).ready(function(){
  $(".datepicker").datepicker({ 
      dateFormat: 'yy-mm-dd',
      showOtherMonths: true,
      selectOtherMonths: true
    });
});

//timepicker 
$(document).ready(function(){
  $(".timeend, .timestart").timepicker({'step': 15});
});

 


//setting up partial goodness
  $(document).ready(function() {   
    $(".iconpencil").click(function() {
      console.log($(this).data("edit-url"));
      var url = $(this).data("edit-url") + ".js"; 
        $.getScript(url, function(result){
          console.log(result);
        });
       
    });
  });

//hide all the extra tasks
  $(document).ready(function(){
    $('.tasks').hide();
     $('.tasks').each(function(index){
    
     if ($(this).attr('data-count') <= 2){
         $(this).show();
         }
      }); 
  });

//link to other tasks and running count
$(document).ready(function(){
   $('.moretasks').hide();
    $('.moretasks').each(function(index){
    if ($(this).data('count') >= 3) {
     $(this).show(); 
         }   
       }); 
     });   

//get date set as default for input field
    $(document).ready(function() {   
    $(".linkdiv").click(function() {
      var date = $(this).data("date"); 
        $('.datestart').val(date);
        });
    });



            
</script>


</header>
  
<!--   <h1>Calendar of Fun</h1> -->

  
</header>

<!-- Rails to establish dates - .to_date converts to string -->
<% start_date = params.fetch(:start_date, Date.today).to_date %>
<% date_range = (start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week).to_a %>

<h4 class= 'text-center'><%= link_to "Previous", start_date: date_range.first - 1.day %>
<!-- change this from number to name of month -->
<%= get_month_name(start_date.month) %> 
<%= start_date.year %>
<%= link_to "Next", start_date: date_range.last + 1.day %></h4>

<table class="container table table-striped table table-bordered">

  <thead >
   <tr class="row seven-cols">
     <th class="col">Sun</th>
     <th class="col">Mon</th>
     <th class="col">Tues</th>
     <th class="col">Wed</th>
     <th class="col">Thurs</th>
     <th class="col">Fri</th>
     <th class="col">Sat</th>
    </tr>
  </thead>
  <tbody>
  <% date_range.each_slice(7) do |week| %>
    
     <tr class="row seven-cols" >
     
      <% week.each do |day| %>
        
      
      <td class='cells col' id=<%= idcreate(day) %> data-day=<%= day %> > 

      <div class = "dateday"  data-toggle="modal"  data-target ='#newModal'>      
       <h5 class = "float-right" > 
       <%= shortday(day) %>
         
       </h5>


        </div>
        <% count = 0 %>
      <% @tasks.select{|m| m.date == day}.each do |task| %>
            <% count = count + 1%>
            
             <div class="tasks" id=<%=task.id%>  data-date=<%=task.date%> data-count=<%=count%>> 
             <%=link_to day_path(task.date) do %>
              <%= task.name %>
              <% end %>
              
                <i class="fa fa-pencil-square-o float-right iconpencil" aria-hidden="true" data-toggle="modal" data-target="#myModal" data-edit-url="<%=edit_task_path(task) %>"></i>
                 
                
                <i class="fa fa-trash float-right icon trash" aria-hidden="true" data-id=<%=task.id%>> </i>

                <i class="fa fa-clone float-right iconcopy" aria-hidden="true"></i>
              

           
           
            
           </div>
         <% end %>
         <div class="moretasks"  data-count=<%=count%>> 
           <%=link_to day_path(day) do %>
           <%=count -2 %> more tasks...
          <% end %>
          </div>
           <div class="linkdiv" data-toggle="modal"  data-target ='#newModal' data-date=<%=day%>>
          </div>
        </td> <!-- td -->
      
     <% end %>
    </tr>
   <% end %>
  </tbody>
</table>
</div>


<br/>
<br/>

<b>Add a <%=link_to "New Task", new_task_path %> to the calendar</b>




<!-- Button trigger modal -->
<!-- <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button> -->

<!-- Modal update -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Update Task</h4>
      </div>
      <div class="modal-body" id="form-placeholder">
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

 

<!--Modal new -->
<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">New Tasks</h4>
      </div>
      <div class="modal-body">
      <%= simple_form_for Task.new,  :html =>{ class: 'booyah-box col-12'} do |f| %>
    <%= f.input :name %>
    <%= f.input :date, :as => :string,  input_html: {class: 'datepicker datestart', value: ''} %>
    <!--<%= f.input :enddate, :as => :string, :label => 'End Date', input_html: {class: 'datepicker'} %> -->
    <%= f.input :starttime, :as => :string, :label => 'Start Time', input_html: {class: 'timestart'}%>
    <%= f.input :time, :as=> :string, :label => 'End Time', input_html: {class: 'timeend'}%>
    <%= f.input :notes %>
    <%= f.submit class: 'btn btn-warning' %>
  <% end %>
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="booyah-box col-6 offset-4">
  <h1 class="text-center">Double Check Your Task Details</h1>

  <%= render partial: "form" %>
</div>

app/views/tasks/show.html.erb
<script>
  $(document).ready(function() {   
    $(".btn-info").click(function() {
      console.log($(this).data("edit-url"));
      var url = $(this).data("edit-url") + ".js"; 
        $.getScript(url, function(result){
          console.log(result);
        });
       });
      });

    $(document).ready(function() {
  $('.btn-danger').click(function(){
    var iddelete = $(this).attr('data-id');
    if (confirm("Are you sure you want to delete this task?")){
     alert(iddelete);
     $(this).parents('.card').remove();
     $(window).unload(function() {
    $.ajax({ type: 'DELETE', url: "http://localhost:3030/tasks/" + iddelete, data:{} });
      });
    


        }
      });
     });


</script>


<div class = "col-6 offset-3 booyah-box">
<h1 class = "text-center"/> <%=datedisplay(@task.date)%> </h1>
<hr/>

<% datetoday = @task.date %>
<!-- sort task date in a variable -->
<%taskstoday = [] %>
<% tasksall = Task.all %>
<% tasksall.each do |day| %>
  <%if datetoday == day.date %>
  <% taskstoday << day %>
  <% end %>
<% end %>


<!-- sort events for the day -->
<% tasksort = taskstoday.sort_by &:starttime %>

<% tasksort.each do |show| %>
<div class="card">
<p><b><%= show.name %></b></p>

<hr class = "boxline"/>
<p> <b>Time:</b> <%= show.starttime.strftime('%l:%M %p')%> to  <%= show.time.strftime('%l:%M %p')%></p>
<hr class = "boxline"/>
<p><b> Notes:</b>
<%= show.notes %></p>
<div class ="text-right">
<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal" data-edit-url="<%=edit_task_path(show) %>">Update</button>
<button type="button" class="btn btn-danger" data-id =<%=show.id%> >Delete</button>
</div>
</div>

<% end %>
<button type="button" class="btn btn-success"> Add New Event</button>

<!-- Modal update -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Update Task</h4>
      </div>
      <div class="modal-body" id="form-placeholder">
      </div>
      <!-- <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div> -->
    </div>
  </div>
</div>